stages:
  preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
    outs:
      - data/processed/cleaned_data.csv  

  feature_selection:
    cmd: python src/features/feature_selection.py
    deps: 
      - data/processed/cleaned_data.csv  
      - src/features/feature_selection.py
    params:
      - feature_selection.test_size  
    outs:
      - data/interim/test.csv
      - data/interim/train.csv

  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/interim/train.csv
    - src/models/model_building.py
    outs:
    - model/model.pkl
  
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - data/interim/test.csv
    - src/models/model_building.py
    - model/model.pkl
    outs:
    - reports/experiment_info.json

  model_registration:
    cmd: python src/models/model_registration.py
    deps:
    - reports/experiment_info.json
    - src/models/model_registration.py
      